# Generated by Django 5.0.2 on 2024-02-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
